-
  branches:
    only:
      - develop
  version: 1.0.{build}
  clone_folder: C:\projects\ComplainTrain\
  init:
  - cmd: 
  environment:
    BUILD_DIR: C:\projects\ComplainTrain
    ASPNETCORE_ENVIRONMENT: Development
  install:
  - cmd: npm install -g bower
  build_script:
  - cmd: >-
      cd %BUILD_DIR%\ComplainTrain.Core

      dotnet restore

      dotnet build

      cd %BUILD_DIR%\ComplainTrain.Web

      dotnet restore

      dotnet build
  test_script:
  - cmd: >-
      cd %BUILD_DIR%\ComplainTrain.Web.Tests

      dotnet restore

      dotnet build

      dotnet test
-
  branches:
    only:
      - master
  version: 1.0.{build}
  clone_folder: C:\projects\ComplainTrain\
  init:
  - cmd: 
  environment:
    BUILD_DIR: C:\projects\ComplainTrain
    ASPNETCORE_ENVIRONMENT: Production
    deploy_password:
      secure: yB6Yy+WxcO7nlTL3CsZSBO+PlDKZlo7RNN+fDk7NfrYuKx06WeCaCjCIKDh9DJeJzrf6tG31Q7VIhPE38GfDQw==
  install:
  - cmd: npm install -g bower
  build_script:
  - cmd: >-
      cd %BUILD_DIR%\ComplainTrain.Core

      dotnet restore

      dotnet build

      cd %BUILD_DIR%\ComplainTrain.Web

      dotnet restore

      dotnet build

      dotnet publish -o %BUILD_DIR%\publish
  artifacts:
  - path: /publish
    name: ComplainTrain
  before_deploy:
  - ps: >-
      $username = "`$complaintrain"
        $password = $env:deploy_password
        $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username,$password)))
        $Headers = @{
          'Authorization' = ('Basic {0}' -f $base64AuthInfo)
          'If-Match'      = '*'
        }
        $apiUrl = "https://complaintrain.scm.azurewebsites.net/api/vfs/site/wwwroot/wwwroot/app_offline.htm"
        $filePath = "app_offline_tmp.htm"
        Invoke-RestMethod -Uri $apiUrl -Headers $Headers -Method PUT -InFile $filePath -ContentType "multipart/form-data"
  after_deploy:
  - ps: >-
      $username = "`$complaintrain"
        $password = $env:deploy_password
        $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username,$password)))
        $Headers = @{
          'Authorization' = ('Basic {0}' -f $base64AuthInfo)
          'If-Match'      = '*'
        }
        $apiUrl = "https://complaintrain.scm.azurewebsites.net/api/vfs/site/wwwroot/wwwroot/app_offline.htm"
        Invoke-RestMethod -Uri $apiUrl -Headers $Headers -Method DELETE  
  deploy:
  - provider: WebDeploy
    server: https://complaintrain.scm.azurewebsites.net:443/msdeploy.axd?site=complaintrain
    website: complaintrain
    username: $complaintrain
    password: 
      secure: yB6Yy+WxcO7nlTL3CsZSBO+PlDKZlo7RNN+fDk7NfrYuKx06WeCaCjCIKDh9DJeJzrf6tG31Q7VIhPE38GfDQw==
    artifact: ComplainTrain
    aspnet_core: true
    aspnet_core_force_restart: true
    on:
      branch: master