-
  branches:
    only:
      - develop
  version: 1.0.{build}
  clone_folder: C:\projects\traincomplain\
  init:
  - cmd: 
  environment:
    BUILD_DIR: C:\projects\traincomplain
    ASPNETCORE_ENVIRONMENT: Development
  install:
  - cmd: npm install -g bower
  build_script:
  - cmd: >-
      cd %BUILD_DIR%\TrainComplain.Core

      dotnet restore

      dotnet build

      cd %BUILD_DIR%\TrainComplain.Web

      dotnet restore

      dotnet build
  test_script:
  - cmd: >-
      cd %BUILD_DIR%\TrainComplain.Web.Tests

      dotnet restore

      dotnet build

      dotnet test
-
  branches:
    only:
      - master
  version: 1.0.{build}
  clone_folder: C:\projects\traincomplain\
  init:
  - cmd: 
  environment:
    BUILD_DIR: C:\projects\traincomplain
    ASPNETCORE_ENVIRONMENT: Production
  install:
  - cmd: npm install -g bower
  build_script:
  - cmd: >-
      cd %BUILD_DIR%\TrainComplain.Core

      dotnet restore

      dotnet build

      cd %BUILD_DIR%\TrainComplain.Web

      dotnet restore

      dotnet build

      dotnet publish -o %BUILD_DIR%\publish
  artifacts:
  - path: /publish
    name: traincomplain
  deploy:
  - provider: WebDeploy
    server: https://traincomplain.scm.azurewebsites.net:443/msdeploy.axd?site=traincomplain
    website: traincomplain
    username: $traincomplain
    password:
      secure: xr8IVoFelVwcJTmWrGqSgThnI4Bq4PuU3enKNObLstwXpl5RbnLVkIHwA/u90V23xMt3Bvt8AvwClt8CFvQvdQ==
    artifact: traincomplain
    aspnet_core: true
    remove_files: false
    aspnet_core_force_restart: true
    on:
      branch: master